### ISSUE TITLE
Параметры страницы исчезают раньше чем заканчивается анимация смены страниц

### ISSUE THREAD

**Issue by stels-cs** [hit2hat/vkui-navigator#11]
Открываем пример [https://vk.com/app7171285](https://vk.com/app7171285)

Кликаем по кнопке (Перейти на панель 2 + параметры)

Жмем кнопку назад в браузере

На видео скорость анимации замедленна, видно что параметры пропали во время анимации
![bug](https://user-images.githubusercontent.com/8437497/74273930-4af4b780-4d22-11ea-804f-573e8f6b4635.gif)

**Comment by hit2hat** [comment]
Модуль больше не поддерживается. Увы.
