### ISSUE TITLE
Не работает settlingHeight={100} на ios.

### ISSUE THREAD

**Issue by duceum** [hit2hat/vkui-navigator#12]
Задаю settlingHeight={100}, но на iphone все равно сразу не открывается на полную высоту.
Cам компонент модального окна в отдельном компоненте.

Задаю вот так:

```
<ConfigProvider webviewType="vkapps" isWebView={true}>
<Stack activePage={this.state.activePage}
			 modals={[
				 	<ItemModal id="itemModal"/>
					
			 ]}
			 >
</Stack>
</ConfigProvider>
```

**Comment by egorprnn** [comment]
В компонент это значение передается, ищите проблему у себя 							https://github.com/hit2hat/vkui-navigator/blob/b150c6c0e20a9e9e61eaef71295a76a7cafb10f3/src/Stack.js#L91

Тем более этот prop работает только если контента на странице столько, что появляется scroll bar. Если его меньше, то он игнорируется.
design by VKUI.
