### ISSUE TITLE
Обновить readme для новой версии

### ISSUE THREAD

**Issue by ekuizhev** [hit2hat/vkui-navigator#14]
![Selection_256](https://user-images.githubusercontent.com/46845084/102162215-d89cb880-3e99-11eb-9918-7ae56b0a1802.png)

Убрать hidePopout (сейчас кстати скрыть popout можно только так "showPopout(null)", но мне лично не принципиально), добавить пояснения для goBack, но может быть что-то еще не заметил)

**Comment by hit2hat** [comment]
Спасибо за проявленный интерес к навигатору, но, наверное, я вас расстрою, поскольку данный модуль больше не поддерживается.
