### ISSUE TITLE
Передача истории панелей в navigator props

### ISSUE THREAD

**Issue by egorprnn** [hit2hat/vkui-navigator#7]
Как насчет реализации передачи history из Page в navigator props?
https://github.com/hit2hat/vkui-navigator/blob/b150c6c0e20a9e9e61eaef71295a76a7cafb10f3/src/Page.js#L16 
https://github.com/hit2hat/vkui-navigator/blob/b150c6c0e20a9e9e61eaef71295a76a7cafb10f3/src/Page.js#L35

**Comment by hit2hat** [comment]
Привет!
Ждите в следующей версии.
